name = "ZipCode"
uuid = "dd22c9d7-f4d3-4c42-a43f-94178bae7e79"
authors = ["Matthew Amos <mamos82@gmail.com>", "ScottPJones <scottjones@alum.mit.edu>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = "1.5"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
